### ISSUE TITLE
Error when forwarding poll/quiz

### ISSUE THREAD

**Issue by ankit-sinha-18** [viperadnan-git/telegram-message-forwarder-bot#1]
2021-04-11T04:01:03.790280+00:00 heroku[worker.1]: Starting process with command `python3 -m bot`
2021-04-11T04:01:04.649398+00:00 heroku[worker.1]: State changed from starting to up
2021-04-11T04:01:09.151090+00:00 app[worker.1]: [2021-04-11 04:01:09,150 - /app/bot/__init__.py - INFO] [-1001278299702]
2021-04-11T04:01:09.157193+00:00 app[worker.1]: [2021-04-11 04:01:09,151 - /app/bot/__init__.py - INFO] [-1001321563599]
2021-04-11T04:01:10.336203+00:00 app[worker.1]: Pyrogram v1.2.8, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
2021-04-11T04:01:10.336228+00:00 app[worker.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)
2021-04-11T04:01:10.336229+00:00 app[worker.1]: 
2021-04-11T04:04:44.883063+00:00 app[worker.1]: [2021-04-11 04:04:44,881 - /app/.heroku/python/lib/python3.7/site-packages/pyrogram/dispatcher.py - ERROR] 'NoneType' object has no attribute 'html'
2021-04-11T04:04:44.883089+00:00 app[worker.1]: Traceback (most recent call last):
2021-04-11T04:04:44.883090+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pyrogram/dispatcher.py", line 223, in handler_worker
2021-04-11T04:04:44.883091+00:00 app[worker.1]:     *args
2021-04-11T04:04:44.883093+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/concurrent/futures/thread.py", line 57, in run
2021-04-11T04:04:44.883093+00:00 app[worker.1]:     result = self.fn(*self.args, **self.kwargs)
2021-04-11T04:04:44.883094+00:00 app[worker.1]:   File "/app/bot/__main__.py", line 11, in work
2021-04-11T04:04:44.883094+00:00 app[worker.1]:     caption = message.caption.html.replace(remove_string, replace_string)
2021-04-11T04:04:44.883095+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'html'
2021-04-11T04:04:45.518226+00:00 app[worker.1]: [2021-04-11 04:04:45,517 - /app/.heroku/python/lib/python3.7/site-packages/pyrogram/dispatcher.py - ERROR] 'NoneType' object has no attribute 'html'
2021-04-11T04:04:45.518237+00:00 app[worker.1]: Traceback (most recent call last):
2021-04-11T04:04:45.518238+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pyrogram/dispatcher.py", line 223, in handler_worker
2021-04-11T04:04:45.518239+00:00 app[worker.1]:     *args
2021-04-11T04:04:45.518240+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/concurrent/futures/thread.py", line 57, in run
2021-04-11T04:04:45.518240+00:00 app[worker.1]:     result = self.fn(*self.args, **self.kwargs)
2021-04-11T04:04:45.518241+00:00 app[worker.1]:   File "/app/bot/__main__.py", line 11, in work
2021-04-11T04:04:45.518241+00:00 app[worker.1]:     caption = message.caption.html.replace(remove_string, replace_string)
2021-04-11T04:04:45.518242+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'html'

Please fix this.

**Comment by viperadnan-git** [comment]
Fixed !

**Comment by ankit-sinha-18** [comment]
This issue fixed but, when **Quiz** forwarded from 
"From Channel" to "To Channel"
It Becomes **Poll**.

You can check in screenshot attached with it.
![Screenshot_2021_0411_160952](https://user-images.githubusercontent.com/72637068/114301173-3dcb8800-9ae1-11eb-89fc-21c9758dd2e5.jpg)
![IMG_20210411_161204](https://user-images.githubusercontent.com/72637068/114301179-49b74a00-9ae1-11eb-8c55-f8dcec8e0458.jpg)

**Comment by viperadnan-git** [comment]
Pyrogram issue !
There is an issue regarding this in pyrogram's repo.

**Comment by ankit-sinha-18** [comment]
Ohh,

I checked in unofficial version of Telegram also,like plus messenger,telegraph and bgram.

When forwarding (send as copy) the quiz from a Channel to another Channel without quotes,it gets forwarded with quotes automatically.

**Comment by viperadnan-git** [comment]
What about group to group ?

**Comment by ankit-sinha-18** [comment]
Same,it gets forwarded with quotes automatically

**Comment by viperadnan-git** [comment]
I think it's pyrogram/Telegram sided. No issue with this repo.
