### ISSUE TITLE
Unable to deploy on my local machine

### ISSUE THREAD

**Issue by omidta** [viperadnan-git/telegram-message-forwarder-bot#30]
I'm trying to deploy it on my pc but I couldn't 
pip 22.2.2 from c:\python\python37\lib\site-packages\pip (python 3.7)
I've got this:

C:\Users\xxxx\Documents\GitHub\Telegram-signal-forwarder\telegram-message-forwarder-bot>python -m bot
[2022-08-12 13:10:00,202 - C:\Users\xxxx\Documents\GitHub\Telegram-signal-forwarder\telegram-message-forwarder-bot\bot\__init__.py - INFO] Welcome, this is the telegram-message-forwarder-bot. initializing...
[2022-08-12 13:10:00,202 - C:\Users\xxxx\Documents\GitHub\Telegram-signal-forwarder\telegram-message-forwarder-bot\bot\__init__.py - INFO] Bot Mode
Traceback (most recent call last):
  File "C:\Python\Python37\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Python\Python37\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Python\Python37\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\xxxx\Documents\GitHub\Telegram-signal-forwarder\telegram-message-forwarder-bot\bot\__init__.py", line 63, in <module>
    with app:
  File "C:\Python\Python37\lib\site-packages\pyrogram\client.py", line 280, in __enter__
    return self.start()
  File "C:\Python\Python37\lib\site-packages\pyrogram\sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "C:\Python\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Python\Python37\lib\site-packages\pyrogram\methods\utilities\start.py", line 58, in start
    is_authorized = await self.connect()
  File "C:\Python\Python37\lib\site-packages\pyrogram\methods\auth\connect.py", line 40, in connect
    await self.load_session()
  File "C:\Python\Python37\lib\site-packages\pyrogram\client.py", line 563, in load_session
    await self.storage.open()
  File "C:\Python\Python37\lib\site-packages\pyrogram\storage\file_storage.py", line 56, in open
    file_exists = path.is_file()
  File "C:\Python\Python37\lib\pathlib.py", line 1387, in is_file
    return S_ISREG(self.stat().st_mode)
  File "C:\Python\Python37\lib\pathlib.py", line 1183, in stat
    return self._accessor.stat(self)

**Comment by viperadnan-git** [comment]
Please use the updated code
