### ISSUE TITLE
REMOVE_STRINGS not working on some messages

### ISSUE THREAD

**Issue by linehman** [viperadnan-git/telegram-message-forwarder-bot#5]
the following error is generated on removing strings from some messages. any suggestion on this?
thanks
` /usr/local/lib/python3.6/dist-packages/pyrogram/dispatcher.py - ERROR] 'NoneType' object has no attribute 'html'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyrogram/dispatcher.py", line 223, in handler_worker
    *args
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/telegram-message-forwarder-bot/bot/__main__.py", line 16, in work
    caption = message.caption.html.replace(string, replace_string)
AttributeError: 'NoneType' object has no attribute 'html'`

**Comment by viperadnan-git** [comment]
Use the latest code
